### ISSUE TITLE
应该是漏提交文件吧

### ISSUE THREAD

**Issue by sengeiou** [yiwent/Mobike#1]
Error:(5, 37) No resource found that matches the given name (at 'background' with value '@drawable/setting_bg').
Error:(230, 37) No resource found that matches the given name (at 'background' with value '@drawable/scan_unlock_button').

**Comment by yiwent** [comment]
双击错误到对应的地方把background那行删除掉

**Comment by yiwent** [comment]
已重新补上漏提交的文件
