### ISSUE TITLE
能提供一下数据库表的设计信息吗？

### ISSUE THREAD

**Issue by JJonCode** [yiwent/Mobike#3]
我想把这个APP的数据库重现并且修改一下，所以想知道数据库是怎么设计的，方便的话可以提供一下吗？感激不尽~

**Comment by JJonCode** [comment]
对了，摩拜应该是更新了很多页面的url，现在APP里有很多页面都是404的状态了，我试着改了一下Buildurl里的一些函数，感觉逻辑上还是有些没弄清楚，所以想麻烦您有空能更新一下这块的连接信息吗？十分感谢

**Comment by yiwent** [comment]
数据库在bmob里面，你注册下给我邮箱，我给你邮箱权限，地址官方的已更改，所以404，这周末我看下有时间更新

**Comment by JJonCode** [comment]
好的，之前没设置邮箱可见，现在好了，这几天小小研究了一下bmob的数据库，基本操作差不多已经了解了，但还是不太熟练，打算这几天再接着研究研究~

**Comment by JJonCode** [comment]
对了，仔细看了一下关于carNub（单车编号）的部分基本全都没写啊，如果要改写成数据库存储的话难度大吗？

**Comment by yiwent** [comment]
看你想要的效果具体逻辑如何喽

**Comment by JJonCode** [comment]
发现了一处bug，就是在使用搜索功能，输入目的地以后，地图会跳转至对应位置然后很快的切换回当前所在的位置，之后无论把中心点移到什么地方，每隔3秒左右地图都会重新显示定位到当前位置，附近的单车位置也会被固定

**Comment by JJonCode** [comment]
还有一个是如果直接在APP内使用webview显示网页，很多新打开的界面上方标题会显示当前访问网页的url地址而不是想要显示的中文标题

**Comment by yiwent** [comment]
1：搜索后再改一个使能位就行了。2：显示地址是因为前一个activity没传标题，或者该地址失效没有标题，原mobike的webview的逻辑就是这样的

**Comment by yiwent** [comment]
不好意思，代码结构很烂，原官方app做得也很烂，经常遇到崩溃，兼容性不好

**Comment by JJonCode** [comment]
还是非常感谢啦，虽然说Bug确实有点小多2333，不过确实也在这期间学到了不少，还是要多码代码啦，很多实际开发中遇到的问题平时想都没想过的  ╮(￣▽￣)╭
